# conda env create -f environment.yml
name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python
  - mkdocs
  - pip:
      - mkdocs-material
      - mkdocs-awesome-pages-plugin
      - mkdocs-exclude
      - mkdocs-pymdownx-material-extras
